import 'package:flutter/material.dart';

class TermsAndConditionsPage extends StatelessWidget {
  const TermsAndConditionsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: true,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Terms and Conditions'),
          automaticallyImplyLeading: true,
        )
      ),
    );
  }
}
      // body: SingleChildScrollView(
      //   padding: const EdgeInsets.all(16.0),
      //   child: const Text(
      //     'Effective Date 5/24/2024\n\n'
      //     'IMPORTANT NOTICE: THESE TERMS REQUIRE BINDING ARBITRATION TO RESOLVE ANY DISPUTE OR CLAIM RELATING TO THESE TERMS, THE SERVICES OR PROPERTIES OR ANY RELATIONSHIP BETWEEN US. ANY SUCH DISPUTE OR CLAIM WILL BE RESOLVED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION OR ARBITRATION. THESE TERMS ALSO CONTAIN A DISCLAIMER OF WARRANTIES AND A DISCLAIMER OF LIABILITY, AS WELL AS A INDEMNIFICATION BY YOU. PLEASE READ THEM CAREFULLY.\n\n'
      //     'Agreement to Terms. This terms of use agreement (these "Terms") constitutes a legally binding contract between Blink, Inc. ("Blink," "we," "us") and you, with respect to your use of all properties (Web sites, mobile applications, or otherwise) owned or operated by Blink and our affiliates (collectively, the "Properties"), and all products and services available from Blink and our affiliates, or other third parties in connection with the Properties (individually and collectively with the Properties, the "Services"). By accessing or using the Services, you acknowledge that you have read, understood, and agree to be bound by, these Terms, our Privacy Policy (Terms and Privacy Policy can be found within the mobile application and at blinkapp.us), including any updates posted here or otherwise communicated to you. If you do not agree to the Terms and the Privacy Policy, please do not use the Services.\n\n'
      //     'Changes to Terms. We may modify these Terms at any time by posting a revised version. Any changes to the Terms will be effective immediately upon posting. Please review the Terms each time you use the Services as your continued use of the Services after such changes will constitute acceptance of, and agreement to, such changes. You waive any right you may have to receive specific notice of such changes.\n\n'
      //     'Consent. You affirm that you are at least 13 years of age in your jurisdiction and are fully able and competent to enter into, and comply with, these Terms. If you are accessing and using the Services on behalf of a company or other legal entity, you represent that you have the authority to bind that entity to these Terms. In that situation, "you" and "your" will refer to both you and that entity.\n\n'
      //     'Our Privacy Policy. Our Privacy Policy, which describes how we collect and use information from our users, is available (Terms and Privacy Policy can be found within the mobile application and at blinkapp.us or by emailing legal@blinkapp.us) as well as through the link titled "Privacy" on our app and other locations within the Properties.\n\n'
      //     'Third Party Materials. The Services may contain links to third party websites, advertisements, services, metadata, offers, activities or other content (collectively, "Third Party Materials"). These Third Party Materials are not owned or controlled by Blink. These Third Party Materials are provided for your reference and convenience only, and do not imply any endorsement, sponsorship or recommendation by Blink.\n\n'
      //     'Grant of Limited License to Users. Subject to your compliance with these Terms, we hereby grant you, as a User, a limited, revocable, non-exclusive, non-transferable and non-sublicensable right to access and use the Services for your personal, non-commercial and informational use only.\n\n'
      //     'Blink Services are Protected. The Services, including all material and information, and the selection, arrangement and composition of such information ("Materials") are proprietary property of Blink, its suppliers, and licensors and are protected by United States and international intellectual property laws, including but not limited to trademark and copyright laws. You agree not to remove, alter or obscure any copyright, trademark or proprietary rights notice incorporated in or accompanying the Services. Except for the limited license explicitly granted to you under these Terms, no other license is granted to you, whether by implication, estoppel or otherwise and all rights are explicitly reserved.\n\n'
      //     'No Reverse Engineering. You may not reverse engineer, decompile, disassemble or otherwise attempt to derive the source code or architectural framework for the Services (except to the extent specifically permitted by applicable law).\n\n'
      //     'No Automated Queries; No Harvesting. You may not access, download, monitor, or copy any information or content contained on or in the Properties or the Services through automated or artificial means (including, but not limited to, screen and database scraping, spiders, robots, crawlers, deep-link, or any similar or equivalent automatic or manual process), or in any way obtain or attempt to obtain any content or information through any means that Blink does not intentionally make available through the Services. However, general purpose Internet search engines and non-commercial public archives that use tools to gather information for the sole purpose of displaying hyperlinks to the Services are granted a limited exception from the foregoing exclusion, provided that they do so from a stable IP address or range of IP addresses using an easily-identifiable agent that adheres to all limitations set forth in any applicable robots.txt file. You may not harvest information about Users for any purpose.\n\n'
      //     'No Improper Uses. You may not frame any part of our Services. You may not use, or attempt to use, the Services through any means not explicitly and intentionally made available, provided or intended with respect to the Services (including, but not limited to, attempting to gain unauthorized access to any portion of the Properties, the Services, or any other systems connected to the Properties and Services). You may not use or access the Properties or the Services in any manner that could damage, disable, overburden, or impair the Services or that could interfere with the rights of or otherwise harm Blink, its service providers, suppliers, other Users or any other person.\n\n'
      //     'Accurate Information. You will be asked to disclose certain information about yourself when you open or confirm your account. You agree to provide us with accurate, complete and up to date information and to keep it updated, complete and correct.\n\n'
      //     'Third Party Authentication. If you use a third party connection function offered through the Services to create an account and login, then you agree that we may access any of your profile information that you have made available to be shared including your profile photo, your email address and your lists and to use it in accordance with these Terms and the Privacy Policy. Please refer to the third party connection policies to manage information that is shared through that account.\n\n'
      //     'Security of Account. You agree you won't disclose your password to anyone and you'll notify us immediately of any unauthorized use of your account. You are responsible for all activities that occur in your account, whether or not you know about them.\n\n'
      //     'Collected Data Definition. You agree and acknowledge that Blink may collect text, lists, photos, videos, comments, reviews, feedback, notes, ideas, know-how, techniques, friend lists, data or other information (individually and collectively, "Information") before, during, and after the provision of Services, or otherwise in connection with the Services (individually and collectively, "Collected Information").\n\n'
      //     'You Are Responsible for User Submissions. The Services may permit you and other Users to submit Information (individually and collectively, "User Submissions"). The person submitting a User Submission, and not Blink, is solely responsible for that person's User Submission and the consequences of submitting it. You acknowledge and agree that Blink has no obligation to pre-screen your or any other person's User Submissions.\n\n'
      //     'Confidentiality of User Submissions. You agree that all User Submissions are not proprietary or confidential. Please be careful what you post, to avoid inadvertently disclosing your address or any other personal information that you do not wish to be seen by the general public.\n\n'
      //     'License to User Submissions. With respect to both User Submissions and Collected Information, you grant Blink a worldwide, non-exclusive, royalty-free, fully paid, perpetual, irrevocable, and fully sub-licensable and transferable license to use, reproduce, distribute, prepare derivative works of, publish, broadcast, publicly perform and display, make, use, import, offer to sell, sell, and otherwise transfer and exploit all copyrights, inventions, and other intellectual property rights in the User Submissions and Collected Information in any form and any medium. We will not pay you or otherwise compensate you for User Submissions or Collected Information.\n\n'
      //     'Do Not Post Illegal or Harmful Content. You agree that you are the exclusive owner of all rights in the User Submissions and such rights have not been assigned or encumbered. You agree not to post, submit or link to any User Submissions or material that infringes, misappropriates or violates the intellectual property or other rights of any third party, or that is in violation of any federal, state or local law, rule or regulation. Additionally, you agree not to post, submit or link to any User Submissions or material that is deceptive, fraudulent, threatening, harassing, defamatory, obscene or otherwise objectionable as determined by Blink.\n\n'
      //     'Do Not Post Improper Content. You agree not to post, submit or link to any User Submissions or material that (i) directly or indirectly directs persons to another online or offline location that provides products or services similar to the Services; (ii) involves unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of solicitation; or (iii) facilitates gambling, gaming, raffles, lotteries, sweepstakes, and/or any other activity featuring the award of a prize.\n\n'
      //     'Review of User Submissions. We do not approve, control or endorse your or anyone else's User Submissions and have no obligation to do so. However, we reserve the right (but assume no obligation) to pre-screen, refuse, remove or modify User Submissions for any reason, at our sole discretion.\n\n'
      //     'Suggestions. If you elect to provide or make available to Blink any suggestions, comments, ideas, improvements or other feedback relating to the Services or otherwise ("Suggestions"), Blink will be free to use, disclose, reproduce, have made, modify, license, transfer and otherwise utilize and distribute your Suggestions in any manner, without credit or compensation to you.\n\n'
      //     'Accuracy of Information. Blink makes no representation or warranty about the accuracy or suitability of the User Submissions or other information displayed on the Properties or provided through the Services.\n\n'
      //     'Account Creation. You do not need to use your real name or image to create a Blink account. However, we ask the following is agreed upon when creating an account to use the Services:\n\n'
      //     'By creating an account, you agree the information submitted will not misrepresent or impersonate any person or business.\n\n'
      //     'a. If you wish to open an account using the trademark or intellectual property of a third party, you must have details publicly visible on your profile at all times that you are not affiliated with them. Failure to do such may result in account suspension or removal at our sole discretion.\n\n'
      //     'By creating an account, you agree to not hold onto handles or any account information with intentions to sell, transfer, or collect them for any reason.\n\n'
      //     'If there is reason to believe there is a violation of these terms, Blink may reach out to inquire as necessary. Failure to respond may result in action being taken on your account.\n\n'
      //     'Third-Party Intellectual Property. All non-Blink trademarks, product names and logos appearing on our Services are property of their respective owners.\n\n'
      //     'Claims of Copyright Infringement. If you believe that your work has been reproduced in connection with the Services in a manner that constitutes copyright infringement, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by sending a written notification to Blink at the address below, with the following information: (i) a physical or electronic signature of the person authorized to act on behalf of the owner of the copyright interest, (ii) identification of the copyrighted work claimed to have been infringed, (iii) a description of where the material that you claim is infringing is located within the Services, (iv) information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an e-mail address, (v) a signed statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law, and (vi) a signed statement that the information in the notification is accurate, and under penalty of perjury, that you are the copyright owner or you are authorized to act on behalf of the owner.\n\n'
      //     'Notification pursuant to the DMCA should be submitted to: legal@blinkapp.us\n\n'
      //     'Trademarks. The Blink name and logo are trademarks of Blink, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Blink.\n\n'
      //     'Warranty Disclaimer THE SERVICES ARE PROVIDED ON AN "AS IS" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, THE Blink PARTIES DISCLAIM ALL WARRANTIES, EXPRESS, IMPLIED, STATUTORY, AND OTHERWISE, IN CONNECTION WITH THE SERVICES AND YOUR USE OF OR TRANSACTIONS WITH Blink, USERS OR OTHER THIRD PARTIES, INCLUDING BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, SECURITY, ACCURACY, AVAILABILITY, USE OF REASONABLE CARE AND SKILL, AND NON-INFRINGEMENT, AS WELL AS WARRANTIES ARISING BY USAGE OF TRADE, COURSE OF DEALING, AND COURSE OF PERFORMANCE.\n\n'
      //     'Limitation of Liability IN NO EVENT WILL THE Blink PARTIES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY COST OF COVER, LOST PROFITS OR DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER ARISING OUT OF, BASED ON, OR RESULTING FROM YOUR USE OF THE SERVICES AND YOUR USE OF, OR TRANSACTIONS WITH, Blink, USERS OR OTHER THIRD PARTIES, WHETHER BASED ON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR ANY OTHER LEGAL THEORY, WHETHER OR NOT SUCH DAMAGES ARE FORESEEABLE AND WHETHER OR NOT Blink IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. IN NO EVENT WILL THE COLLECTIVE LIABILITY OF THE Blink PARTIES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, THE PRIVACY POLICY, THE SERVICES, AND YOUR USE OF, OR TRANSACTIONS WITH, Blink, USERS OR OTHER THIRD PARTIES EXCEED THE LESSER OF (A) THE AMOUNT YOU HAVE PAID TO Blink FOR USE OF THE APPLICABLE SERVICES IN THE PRECEDING TWELVE MONTH PERIOD OR (B) IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO Blink, TEN DOLLARS. Any claims relating to use of the Services must be brought within one (1) year from the date the cause of action arose. Claims brought after such period will be VOID.\n\n'
      //     'Indemnification. You agree to indemnify, defend and hold harmless the Blink Parties from and against any claims, disputes, demands, losses, obligations, liabilities, expenses, damages and costs (including but not limited to attorney's fees) due to or arising out of (1) your access to or use of the Services, (2) your use of, or transactions with, Blink, users or other third parties, or (3) any other violation by you of any of these terms. Blink reserves the right, at its own cost and sole discretion, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Blink in asserting any available defenses.\n\n'
      //     'Arbitration, Venue, Governing Law, and Attorneys' Fees. Any controversy or claim arising out of or relating to these Terms, the Privacy Policy, your access to or use of the Services or the Properties or any relationship between us, including but not limited to the validity, applicability or interpretation of these terms or the privacy policy (any of these, a "Dispute"), including any dispute regarding the scope or enforceability of this arbitration provision, shall be settled exclusively by arbitration administered by the American Arbitration Association in accordance with its then-current Commercial Arbitration Rules ("AAA Rules"), and judgment on the award may be entered in any court having jurisdiction. The place of arbitration shall be Seattle, Washington before a panel of three arbitrators. Pursuant to the Emergency Rules of Protection of the AAA Rules, either party may apply to the arbitrator(s) seeking injunctive relief until the arbitration award is rendered or the controversy is otherwise resolved. The cost of arbitration shall be borne equally by the parties and each party shall be responsible for its own attorneys' fees and expenses, provided that the prevailing party in the arbitration shall be entitled to recover all reasonable attorneys